### PR TITLE
Feature/add queue to registration and donation

### PR DESCRIPTION
**Pull request by shan501**

### CODE REVIEW

**Review by keyan-m — COMMENTED** [review]
There seems to be 3 variables defined in `local-env.sh` which should probably be exported from `env.sh`: `$custodialWalletLabel`, `$custodialWalletsDir` and `$QUEUE`.

I would also suggest further consistency with Boolean values. As far as I understand, we are using 3 truthy values: `"True"`, `"true"`, and `"1"`. But I'm not sure what the Express application expects.

**Comment by shan501** [comment]
yeah , i was gonna manually add it to the local-env.sh file on the ec2 instance. The QUEUE variable will be passed when i run the exec command on node.js.

I am returning a number as a boolean value because it is easier to compare when i get the result in the express app. Where do you see it return "True" or "true"?

**Comment by shan501** [comment]
mmm oh i see, the value i pass into as QUEUE should also be 1 instead of "true"  to be consistent

**Comment by keyan-m** [comment]
`"True"`/`"False"` is returned by some of the `qvf-cli` endpoints. Since changing those requires re-building the binary on the instance, and that this is not a priority, we can keep using `"0"` and `"1"` moving forward and change the `qvf-cli`-related ones later.

**Review by faalbane — APPROVED** [review]

**Pull request merged**
